// <auto-generated />
namespace GoldTeamProject7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Trans2Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Trans2Product));
        
        string IMigrationMetadata.Id
        {
            get { return "201505111905185_Trans2Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
